[redis_nodes]
redis-node-1 ansible_host=172.18.0.6
redis-node-2 ansible_host=172.18.0.2
redis-node-3 ansible_host=172.18.0.3
redis-node-4 ansible_host=172.18.0.4
redis-node-5 ansible_host=172.18.0.5
redis-node-6 ansible_host=172.18.0.7

[redis_nodes:vars]
ansible_user=root
ansible_password=root123
ansible_connection=ssh
ansible_port=22
